In [ ]:
# Mackenzie Brown
# Homework 3 
# 9/11/2026

In [ ]:
print("Problem 1")

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
print("Problem 2")

# 2e) write core for it, document it, include example


def square(var1):
    """
    returns the square of the input
    input: scalar or array of any dimention or numerical type
    output: scalar or array (depends on input), value squared
    """
    z = var1**2 
    return z

array1 = np.arange(0,11,1)
print (array1)
print (square(array1))


integer1 = 3 
print (square(integer1))

print(square(3.3))

print(square(np.arange(0,11,1)))




Problem 2
[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   4   9  16  25  36  49  64  81 100]
9
10.889999999999999
[  0   1   4   9  16  25  36  49  64  81 100]


In [25]:
type([1,2])
type((0,11,1))

tuple

In [ ]:
print("Problem 4")