In [ ]:
# Mackenzie Brown
# Practicum 2 
# 9/21/2026

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print("Problem 1")
# ai prompt: write a code that creates a subsample containing N random draws
# from a Gaussian distribution with a width of omega = 13 and mean of mu = 55

def subsample (N):
    """
    given constant values of omega and mu, calculate gaussian distribution from N draws

    parameter:
    N - number of draws
    return:
    gaussian distribution
    """
    return np.random.normal(55, 13, N) #random values, normal = gaussian
    # fills in specific values of omega and mu, calculate with given N
    

Problem 1


In [16]:
print ("Problem 2")

#print(subsample(10)) # N is equal to 10
sample_values = [] #set equal to empty list to add into 
for i in np.arange(0,10): 
    # loop through 0-9
    sample_gaus = subsample(10) # gaussian with N = 10
    sample_mu = np.mean(sample_gaus) # find mean from sample
    sample_omega = np.std(sample_gaus) # find standard deviation from sample
    sample_values += [i, sample_mu, sample_omega] # add all found values into list
    
sample_values = np.array(sample_values).reshape(10,3) # turn list into array
# shape array into 10 x 3 form
print(sample_values)
    

Problem 2
[[ 0.         55.35872249 12.17375464]
 [ 1.         52.80330334 14.13910963]
 [ 2.         53.60273384 16.95440324]
 [ 3.         49.65664865  8.46252602]
 [ 4.         53.81216363 15.05386231]
 [ 5.         50.6926268  14.06963631]
 [ 6.         58.44083844 11.3278307 ]
 [ 7.         56.45336392 11.97913848]
 [ 8.         53.48278864 17.33281604]
 [ 9.         59.36585887 11.76037251]]


In [22]:
print("Problem 3")
# prompt: write a code creating a subsample containing N=10 random draws, with an omega of
# 13 and mean of 55, for each sample record the sample number (0 to 9), the sample mean
# and the sample standard deviation in an array with one row per sample (10x3 array), write
# in python and use numpy

np.random.seed(42) # set random seed for reproducibility

# parameters 
num_samples_ai = 10
N_ai = 10
mean_ai = 55
omega_ai = 13

#generate 10 samples, each containing N=10 random draws (shape: 10x10)
draws = np.random.normal(loc = mean_ai, scale = omega_ai, size = (num_samples_ai, N_ai))

# calculate metrics across each sample (axis=1)
sample_numbers = np.arange(num_samples_ai).reshape(-1,1)
sample_means = np.mean (draws, axis = 1, keepdims = True)
sample_std = np.std(draws, axis = 1, ddof = 1, keepdims = True)

# combine into 10x3 array
results_array = np.hstack((sample_numbers, sample_means, sample_std))
print("Results Array")
print(results_array)

# my code compares using the np.mean and np.std to find the sample values, except
# my code uses a for loop and ai code does not, they stack the found values of each to 
# make one 10x3 array, i made a list then converted into an array and reshaped 

Problem 3
Results Array
[[ 0.         60.82479445  9.39910833]
 [ 1.         44.72144295  9.81922173]
 [ 2.         52.11603366 10.58067144]
 [ 3.         50.96861334 14.88805026]
 [ 4.         51.71331176 11.7078856 ]
 [ 5.         57.59273856  9.17141171]
 [ 6.         54.80425911 11.44484649]
 [ 7.         54.3794304  17.61124997]
 [ 8.         56.31881662  9.61296438]
 [ 9.         53.06051189  8.4825779 ]]


In [28]:
print("Problem 4")
help(np.savetxt)
np.savetxt("practicum2_kenzb4_array_to_txt_file.txt", results_array,
           header = "Number of Draws is: 10")
# name file, give input (my array), header adds comment to top of page

Problem 4
Help on _ArrayFunctionDispatcher in module numpy:

savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None
)
    Save an array to a text file.

    Parameters
    ----------
    fname : filename, file handle or pathlib.Path
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:

        * a single specifier, ``fmt='%.4e'``, resulting in numbers formatted
          like ``' (%s+%sj)' % (fmt, fmt)``
        * a full string specifying every real

In [33]:
print("Problem 5")



def calculate_results(N):
    """
    given different N values, find 10 samples (find mean and std)
    for each N, sample 10 times, record in 2D array for each, append to file

    parameters:
    N number of random draws

    results:
    array of sample values for each N
    sample values have sample mean and sample omega 
    
    
    """
    sample_values = []

    for i in np.arange(0,9):
        sample_gaus = subsample(N)
        sample_mean = np.mean(sample_gaus)
        sample_omega = np.std(sample_gaus)
        sample_values.append([sample_mean, sample_omega])
        
    return np.array(sample_values)
    

results_100 = calculate_results(100)
results_1000 = calculate_results(1000)
results_10000 = calculate_results(10000)
results_100000 = calculate_results(100000)
results_1000000 = calculate_results(1000000)

print(results_100, "\n", results_1000, "\n", results_10000, "\n",
      results_100000, "\n", results_1000000)
      
      


    
   


Problem 5
[[54.38337284 14.277647  ]
 [54.32009639 12.26386915]
 [55.93826998 13.32744091]
 [53.2599077  12.73475074]
 [54.7153867  11.89268077]
 [55.20015099 13.79598804]
 [55.25431296 12.93947723]
 [55.58011998 12.97811733]
 [54.87412556 11.75628319]] 
 [[55.44128712 13.2245091 ]
 [54.6436587  13.02621874]
 [55.16302424 13.0207257 ]
 [55.42944538 12.39161434]
 [55.29174989 13.02563783]
 [54.13513444 13.24044887]
 [54.68022005 12.89852995]
 [55.19958702 12.98786092]
 [54.70346701 12.93252617]] 
 [[55.30720827 12.96323627]
 [55.01127641 13.16275928]
 [54.78360732 12.98102599]
 [54.86220167 12.97948366]
 [54.87857209 13.08867808]
 [55.02218937 13.09647595]
 [54.97471707 12.94750846]
 [55.0015412  13.13661522]
 [55.00503563 13.05809424]] 
 [[54.93508515 13.01723788]
 [54.97064279 13.00135774]
 [54.96917125 13.00186535]
 [54.99944167 12.99756357]
 [55.00517636 12.99476661]
 [55.01337348 13.06373094]
 [54.96416523 13.02398591]
 [54.99183634 13.02705002]
 [54.95566017 12.95805187]] 
 [[54.9